Config = {}
QBCore = exports['qb-core']:GetCoreObject()
Config.UseTarget =  GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.VehicleCount = 40
Config.CurrentVehicles = {}
Config.Locations = {
    {
        deliver = { coords = vector3(2351.5, 3132.96, 48.2), length = 6.0, width = 4.0, heading = 270.0},
        list = { coords = vector3(2403.51, 3127.95, 48.15), length = 6.0, width = 4.0, heading = 270.0},
        blip = { -- optional, if you dont want blip just delete this table.
            coords = vector3(2397.42, 3089.44, 49.92),
            sprite = 380,
            color = 9,
            display = 4,
            scale = 0.7,
            text = Lang:t('text.scrapyard'),
        }
    }
}



Config.Vehicles = {
    "akuma",
    "alpha",
    "asea",
    "asbo",
    "baller",
    "baller2",
    "banshee",
    "bati",
    "bison",
    "blade",
    "bobcatxl",
    "blista",
    "blista2",
    "buffalo",
    "buffalo2",
    "bullet",
    "carbonrs",
    "cavalcade",
    "cavalcade2",
    "chino",
    "comet2",
    "cognoscenti",
    "dominator",
    "exemplar",
    "f620",
    "felon",
    "feltzer2",
    "fq2",
    "fusilade",
    "gauntlet",
    "huntley",
    "jackal",
    "jester",
    "ninef",
    "ninef2",
    "oracle",
    "oracle2",
    "panto",
    "picador",
    "pigalle",
    "prairie",
    "rhapsody",
    "ratloader2",
    "rebel",
    "rocoto",
    "ruiner",
    "sabregt",
    "schafter2",
    "schwarzer",
    "seminole",
    "sentinel",
    "sentinel2",
    "serrano",
    "slamvan",
    "stanier",
    "stretch",
    "sultan",
    "tampa",
    "tailgater",
    "thrust",
    "turismor",
    "virgo",
    "washington",
    "zion",
    "zion2",
    "zentorno"
}